const fiisData = {
  "COIN11": {
    "ticker": "COIN11",
    "nome": "Buena Vista Neos Bitcoin High Income ETF",
    "tipo": "Criptomoedas (Renda)",
    "preco": "R$ 40,90",
    "vpa": null,
    "recomendacao": "Manter",
    "alerta": 5,
    "explicacoes": "ETF focado em exposição ao Bitcoin com estratégia de Covered Calls para geração de dividendos (renda mensal). Diferente de um FII comum, sua variação de preço depende totalmente do mercado cripto.",
    "pontos_criticos": "Ativo de altíssima volatilidade. A distribuição de renda vem de venda de opções, não de aluguéis ou CDI. Em meses de forte queda do Bitcoin, a geração de renda pode ser corroída pela perda de capital.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "manter",
    "boas_noticias": "Permite transformar a tese de criptomoedas (ativo sem fluxo de caixa) em uma máquina de distribuição mensal com vantagem tributária de ETF.",
    "dividendos_recentes": [
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    "fato_relevante_recente": false
  },
  "AURO11": {
    "ticker": "AURO11",
    "nome": "Buena Vista Neos Gold High Income ETF",
    "tipo": "Ouro (Renda)",
    "preco": "R$ 101,00",
    "vpa": null,
    "recomendacao": "Manter",
    "alerta": 4,
    "explicacoes": "ETF que busca aliar a segurança institucional do Ouro físico (commodity de hedge) com geração de receita por meio de derivativos, pingando dividendo todo mês na conta.",
    "pontos_criticos": "O Ouro não gera valor intrínseco, então o dividendo vem das operações de opções e taxa de juros. Se o mercado de ouro ficar lateralizado sem volatilidade, o ganho das opções diminui.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "manter",
    "boas_noticias": "Ótima tese para blindar a carteira contra crises institucionais e inflação, ganhando para segurar o ativo (dividendos mensais).",
    "dividendos_recentes": [
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0
    ],
    "fato_relevante_recente": false
  },
  "BRCO11": {
    "ticker": "BRCO11",
    "nome": "Bresco Logística FII",
    "tipo": "Tijolo (Logística)",
    "preco": "R$ 116,04",
    "vpa": 116.02,
    "recomendacao": "Manter",
    "alerta": 4,
    "explicacoes": "Fundo logístico classe A+ com portfólio estratégico na Grande SP. Mantém contratos atípicos com inquilinos investment grade. Novo contrato com Expresso 3300 no Bresco Embu zera vacância daquele ativo e deve adicionar ~R$ 0,02/cota ao resultado após carência de 4-6 meses.",
    "pontos_criticos": "Vacância residual de ~4% concentrada em Bresco Canoas e Bresco Resende. WestRock sinalizou saída de Itupeva para 2026 (3% da ABL). Recomposição de portfólio depende de novos contratos em mercado competitivo com Selic elevada.",
    "tendencia_dividendos": "aumentar",
    "tendencia_preco": "manter",
    "boas_noticias": "Contrato com Expresso 3300 no Bresco Embu (100% da ABL daquele ativo) em negociações avançadas. Gestora estuda aquisições de Simões Filho e Viracopos para fortalecer portfólio.",
    "dividendos_recentes": [
      0.87,
      0.87,
      0.87,
      0.87,
      0.87,
      0.87
    ],
    "fato_relevante_recente": true
  },
  "LVBI11": {
    "ticker": "LVBI11",
    "nome": "VBI Logística FII",
    "tipo": "Tijolo (Logística)",
    "preco": "R$ 101,24",
    "vpa": 120.34,
    "recomendacao": "Comprar",
    "alerta": 2,
    "explicacoes": "Fundo logístico de alto padrão com vacância excepcional (1,1%) e inquilinos de grande solidez financeira. Distribuição consistente de R$ 0,75/cota. Gestão VBI com track record sólido em logística de última milha e galpões classe A em regiões prime.",
    "pontos_criticos": "Pequena elevação de vacância projetada para 1,1% por renegociações pontuais. Exposição marginal a inquilinos do varejo eletrônico que atravessam ciclo de ajuste de estoques.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "subir",
    "boas_noticias": "Taxa de ocupação acima de 98,9%, uma das mais elevadas do setor logístico. Rendimento de R$ 0,75/cota mantido com consistência histórica e perspectiva de novos acordos logísticos no pipeline.",
    "dividendos_recentes": [
      0.75,
      0.75,
      0.75,
      0.75,
      0.75,
      0.75
    ],
    "fato_relevante_recente": false
  },
  "HGRU11": {
    "ticker": "HGRU11",
    "nome": "CSHG Renda Urbana FII",
    "tipo": "Tijolo (Renda Urbana)",
    "preco": "R$ 125,00",
    "vpa": 128.87,
    "recomendacao": "Comprar",
    "alerta": 2,
    "explicacoes": "Fundo híbrido da Pátria com portfólio excepcional: WAULT de 9,2-9,5 anos, vacância física de apenas 0,8% e ~100 imóveis em 16 estados. Estratégia de reciclagem ativa comprova geração de valor acima dos laudos. Distribuição de R$ 1,55/cota em jun/25 incluiu ganho de capital de R$ 69,4 mi em venda de imóvel.",
    "pontos_criticos": "Dependência de eficiência na realocação de capital após os desinvestimentos para manter rendimento recorrente. Concentração setorial em educação e varejo de vestuário aumenta correlação com ciclo econômico.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "subir",
    "boas_noticias": "Venda de imóvel em SP por R$ 170 milhões (lucro de R$ 69,4 mi acima do laudo) gerou distribuição extraordinária. WAULT superior a 9 anos com contratos atípicos é um dos maiores do mercado, garantindo previsibilidade máxima.",
    "dividendos_recentes": [
      0.9,
      0.9,
      0.9,
      0.9,
      0.9,
      1.55
    ],
    "fato_relevante_recente": true
  },
  "TVRI11": {
    "ticker": "TVRI11",
    "nome": "Tivio Renda Urbana FII",
    "tipo": "Tijolo (Renda Urbana)",
    "preco": "R$ 98,50",
    "vpa": 104.11,
    "recomendacao": "Vender",
    "alerta": 8,
    "explicacoes": "Fundo de renda urbana com risco estrutural grave: principal inquilino (Banco do Brasil) iniciou rescisões antecipadas de contratos a partir de fev/2026, com vacância podendo atingir 16% até jan/2027. O modelo de agências físicas bancárias enfrenta pressão sistêmica de digitalização. Reserva de R$ 0,56/cota mitiga apenas temporariamente o impacto.",
    "pontos_criticos": "BB notificou rescisão antecipada de contratos representando crescente parcela da receita. Vacância projetada de até 16% até jan/2027 caso não haja novas locações. Contratos bancários remanescentes com vencimento concentrado em 2027 aumentam o risco de vacância estrutural.",
    "tendencia_dividendos": "cair",
    "tendencia_preco": "cair",
    "boas_noticias": "Reserva acumulada de R$ 0,56/cota oferece proteção temporária para distribuições no curto prazo. Gestão busca ativamente diversificação para saúde e varejo, mas a execução ainda está em andamento.",
    "dividendos_recentes": [
      1.03,
      1.03,
      1.03,
      1.03,
      1.03,
      0.99
    ],
    "fato_relevante_recente": true
  },
  "SNAG11": {
    "ticker": "SNAG11",
    "nome": "Suno Agro Fiagro",
    "tipo": "Fiagro (Papel)",
    "preco": "R$ 10,05",
    "vpa": 11.08,
    "recomendacao": "Manter",
    "alerta": 4,
    "explicacoes": "Fiagro da Suno com carteira de CRAs diversificada em 264 devedores e spread de CDI+3,69%. Inadimplência histórica zero e retorno de 264% do CDI em 2025. Distribuição de R$ 0,11/cota isenta de IR. Liquidez diária superior a R$ 10 mi garante negociabilidade.",
    "pontos_criticos": "Exposição ao risco de crédito do agronegócio, setor cíclico sujeito a adversidades climáticas e de preços de commodities. Sensibilidade à queda da Selic comprime o rendimento nominal futuro dos CRAs atrelados ao CDI.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "manter",
    "boas_noticias": "Retorno total de 42,51% em 2025 (264% do CDI) é um dos melhores do segmento. Base de 130 mil cotistas garante liquidez elevada. Alienação estratégica de CRA Boa Safra para diversificação do portfólio.",
    "dividendos_recentes": [
      0.1,
      0.1,
      0.1,
      0.1,
      0.1,
      0.1
    ],
    "fato_relevante_recente": false
  },
  "VISC11": {
    "ticker": "VISC11",
    "nome": "Vinci Shopping Centers FII",
    "tipo": "Tijolo (Shoppings)",
    "preco": "R$ 110,50",
    "vpa": 116.16,
    "recomendacao": "Manter",
    "alerta": 5,
    "explicacoes": "Fundo de shoppings da Vinci com SSS de +6,6% e SSR de +3,8% a.a. confirmando resiliência operacional. Distribuição de R$ 0,80/cota sustentada, mas resultado operacional (~R$ 0,68/cota) está abaixo do distribuído, com diferença coberta por reservas. Exerceu preferência de compra de 25% adicional no Shopping Paralela.",
    "pontos_criticos": "Distribuição supera resultado operacional — usa reservas para cobrir diferença, o que não é sustentável indefinidamente. Alavancagem via CRIs elevada. Inadimplência sazonal de até 8,5% em janeiro. Vacâncias localizadas em shoppings secundários.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "manter",
    "boas_noticias": "SSS de +6,6% a.a. e SSR de +3,8% a.a. indicam crescimento real do varejo nos shoppings. Exercício de preferência no Shopping Paralela fortalece presença em ativo estratégico.",
    "dividendos_recentes": [
      0.8,
      0.8,
      0.8,
      0.8,
      0.85,
      0.85
    ],
    "fato_relevante_recente": true
  },
  "HGLG11": {
    "ticker": "HGLG11",
    "nome": "CSHG Logística FII",
    "tipo": "Tijolo (Logística)",
    "preco": "R$ 153,97",
    "vpa": 166.49,
    "recomendacao": "Comprar",
    "alerta": 3,
    "explicacoes": "Maior fundo logístico da B3 em ABL (Pátria/CSHG) com distribuição consistente de R$ 1,10/cota. Vacância física recuou para 3,5%-5,5% com novas locações no Cone G06 e empreendimentos DCR. Alocação da 10ª emissão em andamento com aquisição em Cariacica/ES concluída.",
    "pontos_criticos": "Alavancagem de 12,1% (14,3% consolidada via SPE) requer monitoramento em cenário de Selic elevada. Saídas programadas de Exito e Eletrobras devem elevar temporariamente a vacância projetada. Custo de carregamento da alavancagem pressiona resultado líquido.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "subir",
    "boas_noticias": "Entrada do Hubhouse em São José dos Campos reduziu vacância local para 2,8%. Nova aquisição em Cariacica/ES confirma estratégia de diversificação geográfica. Gestão reafirmou guidance de R$ 1,10/cota.",
    "dividendos_recentes": [
      1.1,
      1.1,
      1.1,
      1.1,
      1.1,
      1.5
    ],
    "fato_relevante_recente": true
  },
  "TRXF11": {
    "ticker": "TRXF11",
    "nome": "TRX Real Estate FII",
    "tipo": "Tijolo (Renda Urbana)",
    "preco": "R$ 105,00",
    "vpa": 98.79,
    "recomendacao": "Manter",
    "alerta": 5,
    "explicacoes": "Fundo de renda urbana com vacância quase zero (0,22% física / 0,42% financeira) e portfólio premiado: Assaí, Pão de Açúcar, Albert Einstein, Sírio-Libanês, Shopee e ativos educacionais. Contratos atípicos de longo prazo (alguns até 2054) garantem previsibilidade máxima de receita.",
    "pontos_criticos": "Alavancagem financeira de ~39% do PL é a maior preocupação do mercado e pesa sobre o desconto ao VPA (P/VP ~0,93). Emissões frequentes e mudanças de estratégia geraram reputação volátil. Custo financeiro da dívida pressiona resultado em ambiente de Selic elevada.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "manter",
    "boas_noticias": "Vacância financeira de 0,42% é uma das mais baixas do mercado. Contratos atípicos com grandes varejistas e hospitais premium garantem previsibilidade até 2054. Distribuição de R$ 0,93/cota mantida no guidance.",
    "dividendos_recentes": [
      0.9,
      0.9,
      0.9,
      0.93,
      0.93,
      0.93
    ],
    "fato_relevante_recente": true
  },
  "GGRC11": {
    "ticker": "GGRC11",
    "nome": "Zagros Renda Imobiliária FII",
    "tipo": "Tijolo (Logística/Industrial)",
    "preco": "R$ 9,95",
    "vpa": 11.08,
    "recomendacao": "Comprar",
    "alerta": 3,
    "explicacoes": "Fundo logístico/industrial da Zagros Capital com estratégia de reciclagem ativa de portfólio. Vacância atingiu mínima histórica de 0,21% em dezembro/2025 após desinvestimentos estratégicos. WAULT de 5,92 anos garante previsibilidade de receita. Cotação com desconto relevante ao VPA oferece margem de segurança.",
    "pontos_criticos": "Dependência de novos desinvestimentos para sustentar ganhos extraordinários. Concentração setorial em galpões logísticos industriais com inquilinos específicos. Sensibilidade a taxas de juros para precificação de novos ativos.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "subir",
    "boas_noticias": "Desinvestimento do CD Pirituba (R$ 35,25 milhões) com lucro sobre o laudo. Carta de Intenções para aquisição de R$ 125 milhões em ativos do BLMG11 fortalece pipeline. Vacância na mínima histórica após gestão ativa.",
    "dividendos_recentes": [
      0.09,
      0.09,
      0.09,
      0.09,
      0.09,
      0.09
    ],
    "fato_relevante_recente": true
  },
  "XPML11": {
    "ticker": "XPML11",
    "nome": "XP Malls FII",
    "tipo": "Tijolo (Shoppings)",
    "preco": "R$ 112,00",
    "vpa": 110.11,
    "recomendacao": "Manter",
    "alerta": 3,
    "explicacoes": "Fundo de shoppings premium com vacância muito baixa (3,7-4%), inadimplência de apenas 1,7%, SSS de +4,5% e NOI de R$ 130/m² (+10,5% a.a.). Venda estratégica de 9 shoppings por R$ 1,6 bilhão otimizou a estrutura de capital. Portfólio de 26 shoppings com base de 700 mil cotistas.",
    "pontos_criticos": "Necessidade de caixa de ~R$ 285 mi avaliada em 2025 exigiu reciclagem acelerada de portfólio. Alavancagem ainda elevada após as vendas. Gestão requer vigilância sobre concentração de vencimentos de dívida.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "subir",
    "boas_noticias": "Venda de 9 shoppings (R$ 1,6 bi) reequilibrou a estrutura de capital. Vacância de 3,7-4% entre as mais baixas do segmento de shoppings. SSS de +4,5% e inadimplência de 1,7% confirmam excelência operacional.",
    "dividendos_recentes": [
      0.9,
      0.9,
      0.92,
      0.92,
      0.92,
      0.92
    ],
    "fato_relevante_recente": true
  },
  "KNSC11": {
    "ticker": "KNSC11",
    "nome": "Kinea Índices de Preços FII",
    "tipo": "Papel (CRI)",
    "preco": "R$ 88,20",
    "vpa": 8.79,
    "recomendacao": "Comprar",
    "alerta": 2,
    "explicacoes": "FII de papel Kinea com carteira diversificada de CRIs em IPCA e CDI. Gestão profissional de crédito com critérios rigorosos de seleção. Cotação com deságio ao VPA oferece oportunidade de entrada. Distribuições crescentes com carteira 100% adimplente confirmam qualidade dos ativos.",
    "pontos_criticos": "Sensibilidade ao ciclo de juros: queda de Selic/IPCA pressiona rendimentos nominais dos CRIs. Maturação de carteira exige eficiência na realocação de amortizações em ativos com spreads similares.",
    "tendencia_dividendos": "aumentar",
    "tendencia_preco": "subir",
    "boas_noticias": "Carteira 100% adimplente com alocações recentes em taxas atrativas. Deságio ao VPA cria margem de segurança para o investidor. Tendência de rendimentos crescentes com plena alocação da carteira.",
    "dividendos_recentes": [
      0.8,
      0.8,
      0.8,
      0.82,
      0.85,
      0.85
    ],
    "fato_relevante_recente": false
  },
  "XPLG11": {
    "ticker": "XPLG11",
    "nome": "XP Log FII",
    "tipo": "Tijolo (Logística)",
    "preco": "R$ 99,51",
    "vpa": 105.56,
    "recomendacao": "Manter",
    "alerta": 5,
    "explicacoes": "Fundo logístico com ABL expandida para 1,7 milhão de m² após 9ª emissão de R$ 1,2 bi e aquisição de 6 novos imóveis. Distribuição estável de R$ 0,82/cota. Portfólio diversificado com mix de 51% contratos típicos e 49% atípicos. WAULT superior a 5 anos após novos contratos.",
    "pontos_criticos": "Inadimplência de 8% da receita de locação em abril/2026 (6 locatários) é preocupante e requer monitoramento. Vacância física de 8,7% em março/2026 está acima da média do setor logístico. Integração de 6 novos imóveis pode pressionar resultado no curto prazo.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "manter",
    "boas_noticias": "9ª emissão bem-sucedida ampliou ABL em +306 mil m² (R$ 919 mi em novos imóveis). Veículo NE Logistic FII suaviza distribuições. Portfólio diversificado em 1,7 mi m² com inquilinos de qualidade.",
    "dividendos_recentes": [
      0.78,
      0.78,
      0.78,
      0.78,
      0.78,
      0.78
    ],
    "fato_relevante_recente": true
  },
  "MXRF11": {
    "ticker": "MXRF11",
    "nome": "Maxi Renda FII",
    "tipo": "Híbrido (Recebíveis)",
    "preco": "R$ 9,70",
    "vpa": 9.38,
    "recomendacao": "Comprar",
    "alerta": 2,
    "explicacoes": "FII de papel mais popular do Brasil com 1,28 milhão de cotistas. Carteira de CRIs com estrutura conservadora (alienação fiduciária, fiança corporativa, LTV controlado). Distribuição de R$ 0,10/cota isenta de IR com liquidez secundária gigantesca na B3. Caixa financeiro robusto de R$ 69 milhões em renda fixa.",
    "pontos_criticos": "Sensibilidade à variação do IPCA e Selic afeta rendimentos nominais no curto prazo. Tamanho elevado do patrimônio exige volume relevante de novas operações para manutenção de rendimento por cota.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "manter",
    "boas_noticias": "Base de 1,28 milhão de cotistas garante liquidez extraordinária no mercado secundário. Gestão ativa monitora rigorosamente garantias e LTV da carteira. Caixa de R$ 69 milhões proporciona estabilidade de distribuições.",
    "dividendos_recentes": [
      0.1,
      0.1,
      0.1,
      0.1,
      0.1,
      0.1
    ],
    "fato_relevante_recente": false
  },
  "IFRA11": {
    "ticker": "IFRA11",
    "nome": "Itaú FI-Infra Debêntures",
    "tipo": "FI-Infra (Renda Fixa)",
    "preco": "R$ 98,93",
    "vpa": 99.5,
    "recomendacao": "Comprar",
    "alerta": 1,
    "explicacoes": "FI-Infra da Itaú Asset com carteira de debêntures de infraestrutura em setores defensivos (energia, telecom, saneamento). Distribuição de R$ 0,98/cota em junho/2025, isenta de IR para PF. Risco de crédito muito baixo com emissores de grande porte e fluxo de caixa regulatório. Alternativa superior às NTN-Bs em termos de yield real líquido.",
    "pontos_criticos": "Duration longa da carteira torna o valor das cotas sensível à abertura de juros reais (NTN-B). Risco de crédito individual dos emissores das debêntures, ainda que historicamente baixo no segmento de infraestrutura regulada.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "manter",
    "boas_noticias": "Carteira 100% adimplente com spreads médios históricos saudáveis. Distribuição de R$ 0,98/cota em junho/2025 confirma geração consistente de renda. Isenção de IR para PF eleva significativamente o rendimento líquido efetivo.",
    "dividendos_recentes": [
      1.05,
      1.05,
      1.05,
      1.05,
      1.05,
      1.05
    ],
    "fato_relevante_recente": false
  },
  "KNCA11": {
    "ticker": "KNCA11",
    "nome": "Kinea Crédito Agro Fiagro",
    "tipo": "Fiagro (Papel)",
    "preco": "R$ 103,40",
    "vpa": 100.74,
    "recomendacao": "Comprar",
    "alerta": 2,
    "explicacoes": "Fiagro Kinea com carteira diversificada de CRAs em CDI com inadimplência histórica zero. Distribuição de R$ 1,18/cota em junho/2025 (acima do guidance histórico), demonstrando aceleração positiva. Exposição a grandes devedores do agronegócio (bioenergia, defensivos, logística) com garantias robustas.",
    "pontos_criticos": "Exposição ao risco de crédito do agronegócio, setor cíclico sujeito a adversidades climáticas e de preços de commodities. Sensibilidade à queda da Selic que comprime o rendimento nominal dos CRAs atrelados ao CDI.",
    "tendencia_dividendos": "aumentar",
    "tendencia_preco": "subir",
    "boas_noticias": "Distribuição de R$ 1,18/cota em junho/2025 supera média histórica, indicando aceleração dos rendimentos. Adimplência em 100% desde o início confirma qualidade excepcional da gestão de crédito Kinea.",
    "dividendos_recentes": [
      1.0,
      1.0,
      1.05,
      1.05,
      1.1,
      1.1
    ],
    "fato_relevante_recente": false
  },
  "KNRI11": {
    "ticker": "KNRI11",
    "nome": "Kinea Renda Imobiliária FII",
    "tipo": "Híbrido (Tijolo)",
    "preco": "R$ 150,50",
    "vpa": 163.43,
    "recomendacao": "Manter",
    "alerta": 2,
    "explicacoes": "Fundo híbrido premium da Kinea com portfólio de lajes corporativas AAA e galpões logísticos. Vacância física reduzida a 4,56% (maio/2025) com novas locações no Rochaverá (Azumi e Wenda Ingredients). Distribuição de R$ 1,00/cota em junho/2025. Indexação contratual equilibrada entre IPCA (55%) e IGP-M (27%).",
    "pontos_criticos": "Vacância financeira ajustada de 7,21% (considerando carências contratuais) ainda é relevante para lajes corporativas em São Paulo. Taxas de administração e gestão elevadas comparadas a fundos passivos. Ciclo de escritórios ainda em recuperação pós-pandemia.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "manter",
    "boas_noticias": "Novas locações no Rochaverá com inquilinos qualificados (Azumi, Wenda) reduzem vacância de 4,60% para 4,56%. Inadimplência praticamente nula no segmento logístico. Portfólio premium em localização prime garante poder de barganha na renovação.",
    "dividendos_recentes": [
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0
    ],
    "fato_relevante_recente": false
  },
  "KNIP11": {
    "ticker": "KNIP11",
    "nome": "Kinea Rendimentos Imobiliários FII",
    "tipo": "Papel (CRI)",
    "preco": "R$ 90,73",
    "vpa": 93.93,
    "recomendacao": "Comprar",
    "alerta": 2,
    "explicacoes": "Fundo de papel High Grade da Kinea com CRIs atrelados ao IPCA (taxa média de IPCA + 9,46%). Cotação com deságio atrativo ao VPA cria margem de segurança. Carteira diversificada com LTV conservador. Distribuições crescentes de R$ 0,70 a R$ 0,90/cota demonstram trajetória positiva.",
    "pontos_criticos": "Exposição ao IPCA como indexador principal torna o rendimento nominal volátil em períodos de desinflação. Alavancagem via operações compromissadas reversas de 7,7% do PL consome parte do retorno.",
    "tendencia_dividendos": "aumentar",
    "tendencia_preco": "subir",
    "boas_noticias": "Deságio ao VPA de 7,2% oferece excelente ponto de entrada para investidor de longo prazo. Trajetória crescente de distribuições (R$ 0,70 → R$ 0,90/cota) confirma maturação da carteira. Gestão Kinea com track record sólido em crédito imobiliário.",
    "dividendos_recentes": [
      0.7,
      0.75,
      0.8,
      0.85,
      0.9,
      0.9
    ],
    "fato_relevante_recente": false
  },
  "KDIF11": {
    "ticker": "KDIF11",
    "nome": "Kinea Infraestrutura FI-Infra",
    "tipo": "FI-Infra (Renda Fixa)",
    "preco": "R$ 123,89",
    "vpa": 123.11,
    "recomendacao": "Comprar",
    "alerta": 1,
    "explicacoes": "FI-Infra Kinea com carteira de debêntures incentivadas de infraestrutura (95% do PL alocado). Guidance de distribuição robusto de ~R$ 1,45/cota para 2026, sustentado por ganhos realizados em vendas de ativos. Novas alocações em set/2025: Ecovias Minas Goiás e QMC Telecom. Rendimentos isentos de IR para PF.",
    "pontos_criticos": "Duration longa sensibiliza o valor patrimonial à abertura de spreads de crédito e variação do IMA-B. Sofreu ajuste de marcação a mercado em 2025 por elevação de prêmios de crédito corporativo.",
    "tendencia_dividendos": "aumentar",
    "tendencia_preco": "subir",
    "boas_noticias": "Guidance de R$ 1,45/cota para meados de 2026 representa yield excepcional isento de IR. Novas alocações em infraestrutura defensiva (telecom e rodovias) diversificam e fortalecem a carteira. Qualidade média elevada com exposição significativa a ativos AAA.",
    "dividendos_recentes": [
      1.15,
      1.15,
      1.15,
      1.15,
      1.2,
      1.2
    ],
    "fato_relevante_recente": false
  }
};
