const fiisData = {
  "BRCO11": {
    "ticker": "BRCO11",
    "nome": "Bresco Logística FII",
    "tipo": "Tijolo (Logística)",
    "preco": "R$ 116,04",
    "vpa": 118.45,
    "recomendacao": "Comprar",
    "alerta": 3,
    "explicacoes": "Fundo de tijolo de galpões classe A+ com portfólio de alta liquidez. Ocupação estabilizada por contratos de longo prazo, com mais de 86% de inquilinos com rating de grau de investimento. Foco em ativos estrategicamente localizados na região metropolitana de São Paulo.",
    "pontos_criticos": "Vacância física subiu para 7,7% após desocupação da FM Logistic em Canoas e MRO em Embu. WestRock anunciou previsão de saída de Itupeva para abril de 2026, impactando 3% da ABL do fundo.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "subir",
    "boas_noticias": "Celebrado novo contrato de locação com a M. Dias Branco para 15.553 m² em Canoas (47% do imóvel). Fundo possui conversas avançadas para ocupação de áreas remanescentes.",
    "dividendos_recentes": [
      0.87,
      0.87,
      0.87,
      0.87,
      0.87,
      0.87
    ],
    "fato_relevante_recente": true
  },
  "LVBI11": {
    "ticker": "LVBI11",
    "nome": "VBI Logística FII",
    "tipo": "Tijolo (Logística)",
    "preco": "R$ 101,24",
    "vpa": 115.3,
    "recomendacao": "Manter",
    "alerta": 2,
    "explicacoes": "Fundo de galpões logísticos de alto padrão em regiões de alta demanda metropolitana. Roda com taxas de ocupação historicamente muito elevadas e inquilinos de grande solidez financeira.",
    "pontos_criticos": "A vacância física projetada sobe ligeiramente para 1,1% devido a renegociações de contratos programadas. Riscos pontuais de inadimplência de locatários expostos a varejo eletrônico.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "manter",
    "boas_noticias": "Rendimento mensal distribuído de R$ 0,75 por cota, mantendo a estabilidade histórica. Estimativas de queda na vacância com a assinatura de novos acordos logísticos.",
    "dividendos_recentes": [
      0.75,
      0.75,
      0.75,
      0.75,
      0.75,
      0.75
    ],
    "fato_relevante_recente": false
  },
  "HGRU11": {
    "ticker": "HGRU11",
    "nome": "CSHG Renda Urbana FII",
    "tipo": "Tijolo (Renda Urbana)",
    "preco": "R$ 125,00",
    "vpa": 126.15,
    "recomendacao": "Manter",
    "alerta": 2,
    "explicacoes": "Fundo híbrido com excelente histórico de ganho de capital por meio de giro imobiliário ativo. Portfólio focado em varejo e educação em pontos comerciais adensados e de alta liquidez. Qualidade da gestão da CSHG/Pátria se traduz em crescimento constante do VP.",
    "pontos_criticos": "Concentração de receita no setor educacional e varejo de vestuário. O giro ativo traz dependência de novas alocações eficientes após os desinvestimentos.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "manter",
    "boas_noticias": "Venda de ativos imobiliários com lucros expressivos acima do laudo de avaliação, gerando reservas para distribuições extras. Integração bem-sucedida de novos ativos de varejo no caixa do fundo.",
    "dividendos_recentes": [
      0.9,
      0.9,
      0.9,
      0.9,
      0.9,
      1.55
    ],
    "fato_relevante_recente": false
  },
  "TVRI11": {
    "ticker": "TVRI11",
    "nome": "Tivio Renda Urbana FII",
    "tipo": "Tijolo (Renda Urbana)",
    "preco": "R$ 98,50",
    "vpa": 104.2,
    "recomendacao": "Manter",
    "alerta": 4,
    "explicacoes": "Fundo focado em agências bancárias e pontos de varejo comercial com portfólio pulverizado. Apresenta alta estabilidade de renda garantida por contratos de longo prazo com grandes instituições bancárias.",
    "pontos_criticos": "Risco de vacância física de 3% e necessidade de renovação ou venda de ativos de agências físicas em desuso bancário. Dependência de lucros extraordinários de vendas passadas para complementar a renda caixa.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "manter",
    "boas_noticias": "Rendimento por cota mantido em R$ 1,03 por cota (DY anualizado de 14,11%). Reserva de rendimentos acumulada não distribuída forte de R$ 0,56 por cota.",
    "dividendos_recentes": [
      1.03,
      1.03,
      1.03,
      1.03,
      1.03,
      0.99
    ],
    "fato_relevante_recente": false
  },
  "SNAG11": {
    "ticker": "SNAG11",
    "nome": "Suno Agro Fiagro",
    "tipo": "Fiagro (Papel)",
    "preco": "R$ 10,05",
    "vpa": 10.05,
    "recomendacao": "Comprar",
    "alerta": 3,
    "explicacoes": "Fiagro Suno focado em CRAs de alta qualidade (remuneração média de CDI + 2,31%). Negociado próximo ao valor patrimonial (P/VP ~0,99), oferecendo excelente retorno mensal isento de IR para pessoas físicas.",
    "pontos_criticos": "Alta concentração de risco de devedor no grupo Boa Safra Sementes, representando 89% do PL do fundo. Riscos climáticos gerais de quebra de safra.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "subir",
    "boas_noticias": "Inadimplência permanece zerada (0,00%). Fundo possui reservas acumuladas no valor de R$ 0,33 por cota para sustentar proventos mínimos em meses subsequentes.",
    "dividendos_recentes": [
      0.1,
      0.1,
      0.1,
      0.1,
      0.1,
      0.1
    ],
    "fato_relevante_recente": false
  },
  "VISC11": {
    "ticker": "VISC11",
    "nome": "Vinci Shopping Centers FII",
    "tipo": "Tijolo (Shoppings)",
    "preco": "R$ 110,50",
    "vpa": 126.35,
    "recomendacao": "Manter",
    "alerta": 3,
    "explicacoes": "Fundo de shopping centers da Vinci Partners com portfólio diversificado em mais de 20 shoppings. Apresenta consistência histórica de rendimentos baseada na estabilização das vendas do comércio varejista.",
    "pontos_criticos": "Inadimplência líquida de 3% e vacâncias físicas pontuais elevadas em shoppings secundários (Shopping Crystal Curitiba com 26,51% e Center Shopping Rio com 18,20%).",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "manter",
    "boas_noticias": "Conclusão bem-sucedida de aquisição de 5% de participação no Plaza Sul Shopping. Fundo possui reservas acumuladas robustas de R$ 1,21 por cota para sustentar distribuições.",
    "dividendos_recentes": [
      0.8,
      0.8,
      0.8,
      0.8,
      0.85,
      0.85
    ],
    "fato_relevante_recente": true
  },
  "HGLG11": {
    "ticker": "HGLG11",
    "nome": "CSHG Logística FII",
    "tipo": "Tijolo (Logística)",
    "preco": "R$ 153,97",
    "vpa": 152.85,
    "recomendacao": "Comprar",
    "alerta": 2,
    "explicacoes": "Maior fundo logístico em ABL e valor de mercado sob gestão do Pátria. Mantém consistência nas distribuições sustentadas por portfólio robusto e alta liquidez dos imóveis. Iniciou a alocação de recursos da 10ª emissão de cotas.",
    "pontos_criticos": "Alavancagem financeira encerrou em 12,1% do portfólio (14,3% consolidada via SPE). Saídas programadas de inquilinos como Exito e Eletrobras devem elevar a vacância física projetada para 4,6% em fevereiro de 2026.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "subir",
    "boas_noticias": "Primeira aquisição da emissão realizada com sucesso: condomínio logístico estratégico em Cariacica/ES. Entrada do Hubhouse reduziu vacância em São José dos Campos para 2,8%.",
    "dividendos_recentes": [
      1.1,
      1.1,
      1.1,
      1.1,
      1.1,
      1.5
    ],
    "fato_relevante_recente": true
  },
  "TRXF11": {
    "ticker": "TRXF11",
    "nome": "TRX Real Estate FII",
    "tipo": "Tijolo (Renda Urbana)",
    "preco": "R$ 105,00",
    "vpa": 104.9,
    "recomendacao": "Comprar",
    "alerta": 3,
    "explicacoes": "Fundo focado em renda urbana e galpões comerciais locados para grandes redes varejistas (Assaí, Pão de Açúcar, Decathlon, Leroy Merlin). Possui taxas de ocupação extraordinárias, com vacância física de apenas 0,22%.",
    "pontos_criticos": "Uso de alavancagem financeira para financiar o desenvolvimento de ativos imobiliários. Anunciada a aprovação e início da 12ª Emissão de cotas em setembro de 2025.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "subir",
    "boas_noticias": "Rendimento mensal mantido em R$ 0,93 por cota (Yield de 11,31% a.a.). A rentabilidade total histórica superou em muito o IFIX (+77,89% vs. +15,03%).",
    "dividendos_recentes": [
      0.9,
      0.9,
      0.9,
      0.93,
      0.93,
      0.93
    ],
    "fato_relevante_recente": true
  },
  "GGRC11": {
    "ticker": "GGRC11",
    "nome": "Zagros Renda Imobiliária FII",
    "tipo": "Tijolo (Logística/Industrial)",
    "preco": "R$ 9,95",
    "vpa": 11.38,
    "recomendacao": "Manter",
    "alerta": 3,
    "explicacoes": "Fundo focado em ativos logísticos e industriais sob modalidade atípica de locação de longo prazo. Apresenta alta previsibilidade de fluxo com prazo médio ponderado de contratos (WAULT) de 5,92 anos. A liquidez diária dobrou com o desdobramento das cotas.",
    "pontos_criticos": "Elevada dependência de taxas de juros de longo prazo para novos desinvestimentos. Concentração setorial em galpões industriais com inquilinos específicos.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "manter",
    "boas_noticias": "Celebração de Carta de Intenções para adquirir R$ 125 milhões em ativos do BLMG11. A AGE do VTL T11 aprovou a proposta revisada para a compra de ativo logístico em Quatro Barras por R$ 214 milhões.",
    "dividendos_recentes": [
      0.09,
      0.09,
      0.09,
      0.09,
      0.09,
      0.09
    ],
    "fato_relevante_recente": true
  },
  "XPML11": {
    "ticker": "XPML11",
    "nome": "XP Malls FII",
    "tipo": "Tijolo (Shoppings)",
    "preco": "R$ 112,00",
    "vpa": 112.5,
    "recomendacao": "Manter",
    "alerta": 2,
    "explicacoes": "Líder de mercado no segmento de shoppings com portfólio premium. Apresenta forte resiliência operacional com taxas de ocupação muito saudáveis nos principais ativos (Shopping Cidade Jardim, Catarina Fashion Outlet).",
    "pontos_criticos": "Vacância de 5,08% registrada no Caxias Shopping. Eventuais oscilações contábeis decorrentes de reavaliações do valor justo dos ativos.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "subir",
    "boas_noticias": "Rendimento mensal estável distribuído pontualmente de R$ 0,09 (após desdobramento). Alta taxa de ocupação agregada e forte fluxo de vendas do portfólio.",
    "dividendos_recentes": [
      0.9,
      0.9,
      0.92,
      0.92,
      0.92,
      0.92
    ],
    "fato_relevante_recente": false
  },
  "KNSC11": {
    "ticker": "KNSC11",
    "nome": "Kinea Índices de Preços FII",
    "tipo": "Papel (CRI)",
    "preco": "R$ 88,20",
    "vpa": 91.1,
    "recomendacao": "Comprar",
    "alerta": 2,
    "explicacoes": "Fundo Kinea focado em CRIs com flexibilidade de indexadores (CDI e IPCA). Aderente às novas diretrizes de apuração baseadas em lucro contábil. Gestão profissional de crédito imobiliário de baixo risco.",
    "pontos_criticos": "Dependência de taxas de inflação e Selic elevadas para manutenção de yields de dois dígitos. Riscos normais de crédito imobiliário comercial.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "subir",
    "boas_noticias": "Alocação rápida e eficiente de novos recursos captados em emissões recentes com taxas atrativas. Carteira permanece saudável e livre de inadimplência.",
    "dividendos_recentes": [
      0.8,
      0.8,
      0.8,
      0.82,
      0.85,
      0.85
    ],
    "fato_relevante_recente": false
  },
  "XPLG11": {
    "ticker": "XPLG11",
    "nome": "XP Log FII",
    "tipo": "Tijolo (Logística)",
    "preco": "R$ 99,51",
    "vpa": 110.2,
    "recomendacao": "Manter",
    "alerta": 2,
    "explicacoes": "Fundo logístico de tijolo com galpões classe A em hubs de distribuição estratégica. Contratos indexados ao IPCA com vencimentos majoritariamente acima de 36 meses garantem forte solidez.",
    "pontos_criticos": "Inadimplência geral zerada, mas vacâncias físicas pontuais no CD Leroy M em Cabo de Santo Agostinho (10,09%) e Duque de Caxias no RJ (9,63%).",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "manter",
    "boas_noticias": "Construção ativa de novos galpões logísticos e robusto volume de investimentos em FIIs de logística (NE LOGI). Geração de caixa operacional saudável.",
    "dividendos_recentes": [
      0.78,
      0.78,
      0.78,
      0.78,
      0.78,
      0.78
    ],
    "fato_relevante_recente": false
  },
  "MXRF11": {
    "ticker": "MXRF11",
    "nome": "Maxi Renda FII",
    "tipo": "Híbrido (Recebíveis)",
    "preco": "R$ 9,70",
    "vpa": 9.8,
    "recomendacao": "Comprar",
    "alerta": 2,
    "explicacoes": "Fundo imobiliário mais popular do mercado brasileiro, focado em crédito privado (CRIs) de alta qualidade e liquidez. Mantém reservas de lucros e caixa financeiro robusto de R$ 69 milhões em renda fixa.",
    "pontos_criticos": "Passivos operacionais e volatilidade de curto prazo atrelada a índices de inflação. Sensibilidade à variação de Selic.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "manter",
    "boas_noticias": "Rendimento mensal estável distribuído pontualmente. Base de investidores superou 1,28 milhão de cotistas, garantindo liquidez secundária gigantesca.",
    "dividendos_recentes": [
      0.1,
      0.1,
      0.1,
      0.1,
      0.1,
      0.1
    ],
    "fato_relevante_recente": false
  },
  "IFRA11": {
    "ticker": "IFRA11",
    "nome": "Itaú FI-Infra Debêntures",
    "tipo": "FI-Infra (Renda Fixa)",
    "preco": "R$ 98,93",
    "vpa": 99.5,
    "recomendacao": "Comprar",
    "alerta": 1,
    "explicacoes": "Fundo de debêntures incentivadas de infraestrutura gerido pela Itaú Asset com yields reais isentos de IR. Focado em concessionárias de grande porte em setores defensivos de energia, telecomunicações e saneamento.",
    "pontos_criticos": "Risco macroeconômico associado a flutuações de juros reais de longo prazo e taxas Selic. Risco de crédito individual dos emissores das debêntures.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "subir",
    "boas_noticias": "Carteira de crédito 100% adimplente e spreads médios históricos saudáveis. Retorno isento de imposto para pessoas físicas, superando NTN-Bs equivalentes.",
    "dividendos_recentes": [
      1.05,
      1.05,
      1.05,
      1.05,
      1.05,
      1.05
    ],
    "fato_relevante_recente": false
  },
  "KNCA11": {
    "ticker": "KNCA11",
    "nome": "Kinea Crédito Agro Fiagro",
    "tipo": "Fiagro (Papel)",
    "preco": "R$ 103,40",
    "vpa": 102.1,
    "recomendacao": "Comprar",
    "alerta": 2,
    "explicacoes": "Fiagro focado em recebíveis de crédito agrícola administrado pela Kinea com taxas atrativas indexadas ao CDI. Apresenta excelente diversificação entre emissores do agronegócio de grande porte (bioenergia, defensivos, logística).",
    "pontos_criticos": "Exposição às flutuações da Selic que podem reduzir o rendimento nominal futuro. Utilização moderada de operações compromissadas reversas atreladas a CRAs.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "subir",
    "boas_noticias": "Ressaltamos a manutenção de 100% de adimplência na carteira desde o início do fundo. Novas aquisições de CRAs foram concluídas com spreads de crédito elevados.",
    "dividendos_recentes": [
      1.0,
      1.0,
      1.05,
      1.05,
      1.1,
      1.1
    ],
    "fato_relevante_recente": false
  },
  "KNRI11": {
    "ticker": "KNRI11",
    "nome": "Kinea Renda Imobiliária FII",
    "tipo": "Híbrido (Tijolo)",
    "preco": "R$ 150,50",
    "vpa": 162.3,
    "recomendacao": "Manter",
    "alerta": 1,
    "explicacoes": "Fundo híbrido de tijolo com portfólio composto por lajes corporativas classe A e condomínios logísticos premium. Apresenta indexação contratual equilibrada (IPCA 55% e IGP-M 27%) e forte consistência histórica de proventos.",
    "pontos_criticos": "Risco padrão de vacância física temporária em lajes corporativas maduras. Taxas de administração elevadas em relação a fundos passivos.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "manter",
    "boas_noticias": "Taxa de vacância sob controle nos imóveis de SP e RJ, com inadimplência agregada praticamente nula nas locações logísticas. A gestão ativa segue focada na renovação contratual favorável.",
    "dividendos_recentes": [
      1.0,
      1.0,
      1.0,
      1.0,
      1.0,
      1.0
    ],
    "fato_relevante_recente": false
  },
  "KNIP11": {
    "ticker": "KNIP11",
    "nome": "Kinea Rendimentos Imobiliários FII",
    "tipo": "Papel (CRI)",
    "preco": "R$ 90,73",
    "vpa": 97.8,
    "recomendacao": "Comprar",
    "alerta": 2,
    "explicacoes": "Fundo de papel de baixo risco (High Grade) focado em CRIs atrelados à inflação (IPCA + taxa média de 9,46%). Possui excelente consistência na geração de renda protegida de oscilações cambiais ou de mercado corporativo.",
    "pontos_criticos": "Inadimplência praticamente nula, mas volatilidade pontual nas distribuições devido a deflações sazonais do IPCA. Alavancagem via compromissadas reversas consome cerca de 7,7% do PL.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "subir",
    "boas_noticias": "Cotação negociada com deságio atrativo na B3 frente ao valor patrimonial. Distribuições mensais consistentes na faixa de R$ 0,70 a R$ 0,90 por cota.",
    "dividendos_recentes": [
      0.7,
      0.75,
      0.8,
      0.85,
      0.9,
      0.9
    ],
    "fato_relevante_recente": false
  },
  "KDIF11": {
    "ticker": "KDIF11",
    "nome": "Kinea Infraestrutura FI-Infra",
    "tipo": "FI-Infra (Renda Fixa)",
    "preco": "R$ 123,89",
    "vpa": 120.4,
    "recomendacao": "Comprar",
    "alerta": 1,
    "explicacoes": "Fundo de infraestrutura Kinea focado em debêntures de baixo risco (35% AAA). Oferece proteção inflacionária com alíquota zero de IR nos rendimentos mensais atrelados ao IPCA. A duration média da carteira é de 6,01 anos.",
    "pontos_criticos": "Desafios macro de spreads de crédito corporativo e oscilações do IMA-B. Eventuais amortizações antecipadas de debêntures na carteira.",
    "tendencia_dividendos": "manter",
    "tendencia_preco": "subir",
    "boas_noticias": "Rendimento mensal elevado para R$ 1,30 por cota em outubro, correspondendo a um Dividend Yield de 11,9% nos últimos 12 meses. O fundo continua negociado com deságio de 1,42% na B3.",
    "dividendos_recentes": [
      1.15,
      1.15,
      1.15,
      1.15,
      1.2,
      1.2
    ],
    "fato_relevante_recente": false
  }
};
